spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/dev
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true